#ifndef GPIO_H
#define GPIO_H 

#define EIMSK_EXT_INTERRUPT_REQUEST_ENABLE_ON_BOTH_INT1_AND_INT0 (unsigned char)0x03
#define EICRA_FALLING_EDGE_INTERRUPT_ON_BOTH_INT1_AND_INT0 (unsigned char)0x0A
#define EIFR_CLEAR_PENDING_INT_INTERRUPTS (unsigned char)0x03

#define MOTOR_DRIVER_INPUT_MASK 0x0F
#define MOTOR_DRIVER_INPUT_BIT_SHIFT 2
#define MOTOR_DRIVER_PINS_MASK (MOTOR_DRIVER_INPUT_MASK << MOTOR_DRIVER_INPUT_BIT_SHIFT)
#define MOTOR_DRIVER_OFF_POSITION (unsigned char)(0x0C << MOTOR_DRIVER_INPUT_BIT_SHIFT)
#define MOTOR_DRIVER_CLOCKWISE_DRIVE (unsigned char)(0x05 << MOTOR_DRIVER_INPUT_BIT_SHIFT)
#define MOTOR_DRIVER_COUNTER_CLOCKWISE_DRIVE (unsigned char)(0x0A << MOTOR_DRIVER_INPUT_BIT_SHIFT)
#define MOTOR_OFF_COMMAND_PIN PD6
#define PD6 6

void IoConfig(void);

#endif //GPIO_H